server:
    port:8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/lojagames
        username: postgres
        password: dafne0904
        driver-class-name: org.postgresql.Driver
        initialize: true
    
    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
    
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
    
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
            location: C:/uploads/temp
            
